import fs from 'fs'
import path from 'path'

const PAGES_DIR = path.join(process.cwd(), 'src', 'pages')
const defaultMeta = {}

main()

async function main() {
  const metaList = await getPageMetaList()
  console.log(
    `/** Auto-generated by preBuild.mjs */\nimport { Meta } from './page'\n\nexport const metaList: Meta[] = ${JSON.stringify(
      metaList.filter((meta) => meta.isPublished),
      undefined,
      2,
    )}`,
  )
}

export async function getPageMetaList() {
  const nodes = await fs.promises.readdir(PAGES_DIR)
  const pages = nodes.filter((n) => /^[^_][^.]+\.(mdx|tsx)/.test(n))
  return Promise.all(pages.map(getPageMeta))
}

/**
 * @returns {Promise<import('../src/models/page').Meta>}
 */
export async function getPageMeta(filePath) {
  const [fileName] = filePath.split(path.sep).slice(-1)
  const [slug, ext] = fileName.split('.')

  const content = await fs.promises.readFile(
    path.join(PAGES_DIR, filePath),
    'utf-8',
  )

  const getMetaRegex = /export const meta = \{([^}]+)\}/

  const metaRaw = getMetaRegex.exec(content)?.[1] ?? ''

  try {
    return {
      author: 'Brian Ingles',
      slug: slug === 'index' ? '' : slug,
      ext,
      ...metaRaw
        .split('\n')
        .filter((line) => line)
        .reduce((meta, line) => {
          const [key, value] = line.trim().split(':')

          // parse array
          const [, array] = /\[([^\]]+)\]/.exec(value) ?? []
          const [, bool] = /^\s*(false|true)/.exec(value) ?? []

          if (array) {
            const items = array
              .split(',')
              .map((item) => item.replace(/^\s*'(.*)'$/, '$1'))

            meta[key] = items
          } else if (bool) {
            meta[key] = bool === 'true'
          } else {
            meta[key] = value.slice(2, -2)
          }
          return meta
        }, {}),
    }
  } catch {
    return defaultMeta
  }
}
