/** Auto-generated by preBuild.mjs */
import { Meta } from './page'

export const metaList: Meta[] = [
  {
    "author": "Brian Ingles",
    "slug": "character-animation",
    "ext": "mdx",
    "title": "Character Animation",
    "date": "2023-03-19"
  },
  {
    "author": "Brian Ingles",
    "slug": "css-grid",
    "ext": "mdx",
    "title": "CSS Grid",
    "date": "2023-03-19"
  },
  {
    "author": "Brian Ingles",
    "slug": "dad-vs-judah",
    "ext": "mdx",
    "title": "Dad vs Judah Game",
    "date": "2023-04-10",
    "tags": [
      "games",
      "godot"
    ]
  },
  {
    "author": "Brian Ingles",
    "slug": "",
    "ext": "tsx",
    "title": "Home",
    "date": "2023-03-19"
  },
  {
    "author": "Brian Ingles",
    "slug": "mandalorian",
    "ext": "mdx",
    "title": "Mandalorian",
    "date": "2023-04-06",
    "tags": [
      "animation",
      "imphenzia"
    ]
  },
  {
    "author": "Brian Ingles",
    "slug": "ninja-animation",
    "ext": "mdx",
    "title": "Ninja Animation",
    "date": "2023-03-20"
  },
  {
    "author": "Brian Ingles",
    "slug": "ninja2d",
    "ext": "mdx",
    "title": "Ninja 2D",
    "date": "2023-04-06",
    "tags": [
      "animation",
      "imphenzia",
      "2D"
    ]
  },
  {
    "author": "Brian Ingles",
    "slug": "pirate",
    "ext": "mdx",
    "title": "Pirate",
    "date": "2023-04-06",
    "tags": [
      "animation",
      "imphenzia"
    ]
  },
  {
    "author": "Brian Ingles",
    "slug": "threejs-animation",
    "ext": "mdx",
    "title": "Three.js Animation",
    "date": "2023-03-19"
  }
]
